export enum EstatusMovimiento {
  TRANSITO = 'TRANSITO',
  TRANSITO_PARCIAL = 'TRANSITO_PARCIAL',
  SOLICITADO = 'SOLICITADO',
  APROBADO = 'APROBADO',
  CANCELADO = 'CANCELADO',
  FINALIZADO = 'FINALIZADO',
}
