export const TiposMuestrasToCreate = [
  { nombre: 'Orina de 24 Horas' },
  { nombre: 'Suero' },
  { nombre: 'Papel Filtro' },
  { nombre: 'LCR' },
  { nombre: 'Sagre EDTA' },
  { nombre: 'Orina' },
  { nombre: 'Plasma Heparina' },
  { nombre: 'Plasma Citrato' },
  { nombre: 'Saliva' },
  { nombre: 'Semen' },
  { nombre: 'Alimentos' },
  { nombre: 'Sangre Total' },
  { nombre: 'Secresión' },
  { nombre: 'Heces' },
  { nombre: 'Lito/Calculo' },
  { nombre: 'Sangre Heparina' },
  { nombre: 'Medula Osea' },
  { nombre: 'Liquído' },
  { nombre: 'Plasma EDTA' },
  { nombre: 'Tubo Rojo sin centrifugar' },
  { nombre: 'Secresión Vaginal' },
  { nombre: 'Absceso' },
  { nombre: 'Espectoración/Flema' },
  { nombre: 'Punta de Cateter' },
  { nombre: '1ra Copro' },
  { nombre: '2da Copro' },
  { nombre: 'Líquidos' },
  { nombre: 'Orina de 2 Horas' },
];
